package view;

import controller.ControlaDoação;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Acompanhamento;
import javax.swing.JOptionPane;

/**
 * Frame criado para acompanhamento posterior a doações de animais realizadas
 * @author Guilherme Bernardelli
 * @since Iniciada 06/04/2016
 */
public class FrameAcompanhamento extends javax.swing.JFrame {

    Acompanhamento acompanhamento;
    ControlaDoação manterAcompanhamento = new ControlaDoação(); 
    
    
    public FrameAcompanhamento() {
        initComponents();
        
        
    }
    public final void carregaLista(){
        try {
            cmbAnimal.removeAllItems();
            ResultSet rs = manterAcompanhamento.listarAnimaisDoados();
            cmbAnimal.addItem(rs.getString("animal"));
            while(rs.next()){
                cmbAnimal.addItem(rs.getString("animal"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FrameDoação.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAcompanhamento = new javax.swing.JPanel();
        chkEmAcompanhamento = new javax.swing.JCheckBox();
        lbDataInicio = new javax.swing.JLabel();
        lbDataFinal = new javax.swing.JLabel();
        tfDataFinal = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            tfDataFinal = new javax.swing.JFormattedTextField(data);
        }
        catch(Exception e){
        }
        tfDataInicio = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            tfDataInicio = new javax.swing.JFormattedTextField(data);
        }
        catch(Exception e){
        }
        lbUltimaVisita = new javax.swing.JLabel();
        lbProximaVisita = new javax.swing.JLabel();
        tfUltimaVisita = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            tfUltimaVisita = new javax.swing.JFormattedTextField(data);
        }
        catch(Exception e){
        }
        tfProximaVisita = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            tfProximaVisita = new javax.swing.JFormattedTextField(data);
        }
        catch(Exception e){
        }
        lbUltimaVacina = new javax.swing.JLabel();
        lbProximaVacina = new javax.swing.JLabel();
        PanelCondição = new javax.swing.JPanel();
        chkCondiçãoVacina = new javax.swing.JCheckBox();
        chkCondiçãoAlimentação = new javax.swing.JCheckBox();
        chkCondiçãoLocal = new javax.swing.JCheckBox();
        chkCondiçãoAtual = new javax.swing.JCheckBox();
        chkCondiçãoLimpeza = new javax.swing.JCheckBox();
        tfProximaVacina = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            tfProximaVacina = new javax.swing.JFormattedTextField(data);
        }
        catch(Exception e){
        }
        tfUltimaVacina = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            tfUltimaVacina = new javax.swing.JFormattedTextField(data);
        }
        catch(Exception e){
        }
        PanelAnimal = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        cmbAnimal = new javax.swing.JComboBox<>();
        PanelButtons = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acompanhamento de Doações");
        setLocation(new java.awt.Point(400, 150));
        setResizable(false);

        chkEmAcompanhamento.setText("Em Acompanhamento");

        lbDataInicio.setText("Data Inicio:");

        lbDataFinal.setText("Data Final:");

        lbUltimaVisita.setText("Ultima Visita:");

        lbProximaVisita.setText("Próxima Visita:");

        lbUltimaVacina.setText("Ultima Vacina:");

        lbProximaVacina.setText("Próxima Vacina:");

        PanelCondição.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Condição:"));

        chkCondiçãoVacina.setText("Vacinas");

        chkCondiçãoAlimentação.setText("Alimentação");

        chkCondiçãoLocal.setText("Local");

        chkCondiçãoAtual.setText("Tratamento");

        chkCondiçãoLimpeza.setText("Limpeza");

        javax.swing.GroupLayout PanelCondiçãoLayout = new javax.swing.GroupLayout(PanelCondição);
        PanelCondição.setLayout(PanelCondiçãoLayout);
        PanelCondiçãoLayout.setHorizontalGroup(
            PanelCondiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCondiçãoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(chkCondiçãoVacina)
                .addGap(18, 18, 18)
                .addComponent(chkCondiçãoAlimentação)
                .addGap(18, 18, 18)
                .addComponent(chkCondiçãoLocal)
                .addGap(18, 18, 18)
                .addComponent(chkCondiçãoAtual)
                .addGap(18, 18, 18)
                .addComponent(chkCondiçãoLimpeza)
                .addGap(33, 33, 33))
        );
        PanelCondiçãoLayout.setVerticalGroup(
            PanelCondiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCondiçãoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCondiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCondiçãoVacina)
                    .addComponent(chkCondiçãoAlimentação)
                    .addComponent(chkCondiçãoLocal)
                    .addComponent(chkCondiçãoAtual)
                    .addComponent(chkCondiçãoLimpeza))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelAcompanhamentoLayout = new javax.swing.GroupLayout(PanelAcompanhamento);
        PanelAcompanhamento.setLayout(PanelAcompanhamentoLayout);
        PanelAcompanhamentoLayout.setHorizontalGroup(
            PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAcompanhamentoLayout.createSequentialGroup()
                .addComponent(chkEmAcompanhamento)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelAcompanhamentoLayout.createSequentialGroup()
                .addGroup(PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAcompanhamentoLayout.createSequentialGroup()
                        .addGroup(PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAcompanhamentoLayout.createSequentialGroup()
                                .addComponent(lbDataFinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(PanelAcompanhamentoLayout.createSequentialGroup()
                                .addComponent(lbDataInicio)
                                .addGap(7, 7, 7)))
                        .addGroup(PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(tfDataFinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUltimaVisita)
                            .addComponent(lbProximaVisita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfProximaVisita)
                            .addComponent(tfUltimaVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAcompanhamentoLayout.createSequentialGroup()
                                .addComponent(lbUltimaVacina)
                                .addGap(18, 18, 18))
                            .addGroup(PanelAcompanhamentoLayout.createSequentialGroup()
                                .addComponent(lbProximaVacina)
                                .addGap(9, 9, 9)))
                        .addGroup(PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUltimaVacina, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(tfProximaVacina)))
                    .addGroup(PanelAcompanhamentoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(PanelCondição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        PanelAcompanhamentoLayout.setVerticalGroup(
            PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAcompanhamentoLayout.createSequentialGroup()
                .addComponent(chkEmAcompanhamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataInicio)
                    .addComponent(tfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUltimaVisita)
                    .addComponent(tfUltimaVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUltimaVacina)
                    .addComponent(tfUltimaVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAcompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataFinal)
                    .addComponent(tfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProximaVisita)
                    .addComponent(tfProximaVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProximaVacina)
                    .addComponent(tfProximaVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelCondição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lbNome.setText("Nome do Animal:");

        jLabel1.setText("Codigo de Acompanhento:");

        tfCodigo.setEnabled(false);

        cmbAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...." }));
        cmbAnimal.setName("cmbAnimal"); // NOI18N
        cmbAnimal.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbAnimalPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout PanelAnimalLayout = new javax.swing.GroupLayout(PanelAnimal);
        PanelAnimal.setLayout(PanelAnimalLayout);
        PanelAnimalLayout.setHorizontalGroup(
            PanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAnimalLayout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmbAnimal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCodigo))
                .addGap(19, 19, 19))
        );
        PanelAnimalLayout.setVerticalGroup(
            PanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonsLayout = new javax.swing.GroupLayout(PanelButtons);
        PanelButtons.setLayout(PanelButtonsLayout);
        PanelButtonsLayout.setHorizontalGroup(
            PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSalvar)
                .addGap(18, 18, 18)
                .addComponent(btBuscar)
                .addGap(18, 18, 18)
                .addComponent(btAlterar)
                .addGap(18, 18, 18)
                .addComponent(btExcluir)
                .addGap(18, 18, 18)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addContainerGap())
        );
        PanelButtonsLayout.setVerticalGroup(
            PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelButtonsLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btBuscar)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir)
                    .addComponent(btLimpar)
                    .addComponent(btVoltar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelAcompanhamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAcompanhamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        cmbAnimal.setSelectedIndex(-1);
        tfCodigo.setText("");
        chkEmAcompanhamento.setSelected(false);
        tfUltimaVisita.setText("");
        tfProximaVisita.setText("");
        tfUltimaVacina.setText("");
        tfProximaVacina.setText("");
        chkCondiçãoVacina.setSelected(false);
        chkCondiçãoAtual.setSelected(false);
        chkCondiçãoAlimentação.setSelected(false);
        chkCondiçãoLocal.setSelected(false);
        chkCondiçãoLimpeza.setSelected(false);
        tfDataInicio.setText("");
        tfDataFinal.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
        try {
            if(manterAcompanhamento.listarAnimaisDoados() == null){
                JOptionPane.showMessageDialog(this,"Nenhuma doação cadastrada");
            }
            else{               
                acompanhamento = new Acompanhamento();
                acompanhamento.setAnimal(cmbAnimal.getItemAt(cmbAnimal.getSelectedIndex()));
                acompanhamento.setEmAcompanhamento(chkEmAcompanhamento.isSelected());
                acompanhamento.setUltimaVisita(tfUltimaVisita.getText());
                acompanhamento.setProximaVisita(tfProximaVisita.getText());
                acompanhamento.setUltimaVacina(tfUltimaVacina.getText());
                acompanhamento.setProximaVacina(tfProximaVacina.getText());
                acompanhamento.setCondiçãoVacinas(chkCondiçãoVacina.isSelected());
                acompanhamento.setCondiçãoAtual(chkCondiçãoAtual.isSelected());
                acompanhamento.setCondiçãoAlimentação(chkCondiçãoAlimentação.isSelected());
                acompanhamento.setCondiçãoLocal(chkCondiçãoLocal.isSelected());
                acompanhamento.setCondiçãoLimpeza(chkCondiçãoLimpeza.isSelected());
                acompanhamento.setDataInicio(tfDataInicio.getText());
                acompanhamento.setDataFinal(tfDataFinal.getText());
                try {
                    manterAcompanhamento.criarAcompanhamento(acompanhamento);
                } catch (ClassNotFoundException | SQLException | IOException ex) {
                    Logger.getLogger(FrameAcompanhamento.class.getName()).log(Level.SEVERE, null, ex); 
                }
                btLimparActionPerformed(evt);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FrameAcompanhamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        ResultSet rs;
        
        try{
            if( manterAcompanhamento.buscarAcompanhamento(cmbAnimal.getItemAt(cmbAnimal.getSelectedIndex()))== null){
                JOptionPane.showMessageDialog(this,"Nenhum acompanhamento cadastrado");
            }
            else{
                rs = manterAcompanhamento.buscarAcompanhamento(cmbAnimal.getItemAt(cmbAnimal.getSelectedIndex())); 
                tfCodigo.setText(rs.getString("codigo"));                
                chkEmAcompanhamento.setSelected(rs.getBoolean("emAcompanhamento"));
                tfUltimaVisita.setText(rs.getString("ultimaVisita"));
                tfProximaVisita.setText(rs.getString("proximaVisita"));
                tfUltimaVacina.setText(rs.getString("ultimaVacina"));
                tfProximaVacina.setText(rs.getString("proximaVacina"));
                chkCondiçãoVacina.setSelected(rs.getBoolean("condiçãoVacina"));
                chkCondiçãoAtual.setSelected(rs.getBoolean("condiçãoAtual"));
                chkCondiçãoLocal.setSelected(rs.getBoolean("condiçãoLocal"));
                chkCondiçãoAlimentação.setSelected(rs.getBoolean("condiçãoAlimentação"));
                chkCondiçãoLimpeza.setSelected(rs.getBoolean("condiçãoLimpeza"));
                tfDataInicio.setText(rs.getString("dataInicio"));
                tfDataFinal.setText(rs.getString("dataFinal"));
                btSalvar.setEnabled(false);
            } //fim do if
        }catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FrameAcompanhamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        
       try{
            manterAcompanhamento.receberExcluirAcompanhamento(cmbAnimal.getItemAt(cmbAnimal.getSelectedIndex()));
            btSalvar.setEnabled(true);
            btAlterar.setEnabled(true);
            btBuscar.setEnabled(true);
            btLimparActionPerformed(evt);
        }
        catch(ClassNotFoundException | SQLException ex){
             Logger.getLogger(FrameDoação.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
       
        try{
            
            acompanhamento = new Acompanhamento();
            acompanhamento.setAnimal(cmbAnimal.getItemAt(cmbAnimal.getSelectedIndex()));
            acompanhamento.setCodigo(tfCodigo.getText());
            acompanhamento.setEmAcompanhamento(chkEmAcompanhamento.isSelected());
            acompanhamento.setUltimaVisita(tfUltimaVisita.getText());
            acompanhamento.setProximaVisita(tfProximaVisita.getText());
            acompanhamento.setUltimaVacina(tfUltimaVacina.getText());
            acompanhamento.setProximaVacina(tfProximaVacina.getText());
            acompanhamento.setCondiçãoVacinas(chkCondiçãoVacina.isSelected());
            acompanhamento.setCondiçãoAtual(chkCondiçãoAtual.isSelected());
            acompanhamento.setCondiçãoAlimentação(chkCondiçãoAlimentação.isSelected());
            acompanhamento.setCondiçãoLocal(chkCondiçãoLocal.isSelected());
            acompanhamento.setCondiçãoLimpeza(chkCondiçãoLimpeza.isSelected());
            acompanhamento.setDataInicio(tfDataInicio.getText());
            acompanhamento.setDataFinal(tfDataFinal.getText());
            
            manterAcompanhamento.receberAcompanhamentoAtualizar(acompanhamento, cmbAnimal.getItemAt(cmbAnimal.getSelectedIndex()));
        }
        catch(ClassNotFoundException | SQLException ex){
             Logger.getLogger(FrameDoação.class.getName()).log(Level.SEVERE, null, ex);
        }         
    }//GEN-LAST:event_btAlterarActionPerformed

    private void cmbAnimalPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbAnimalPopupMenuWillBecomeVisible
        carregaLista();
    }//GEN-LAST:event_cmbAnimalPopupMenuWillBecomeVisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAcompanhamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAcompanhamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAcompanhamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAcompanhamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameAcompanhamento().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAcompanhamento;
    private javax.swing.JPanel PanelAnimal;
    private javax.swing.JPanel PanelButtons;
    private javax.swing.JPanel PanelCondição;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JCheckBox chkCondiçãoAlimentação;
    private javax.swing.JCheckBox chkCondiçãoAtual;
    private javax.swing.JCheckBox chkCondiçãoLimpeza;
    private javax.swing.JCheckBox chkCondiçãoLocal;
    private javax.swing.JCheckBox chkCondiçãoVacina;
    private javax.swing.JCheckBox chkEmAcompanhamento;
    private javax.swing.JComboBox<String> cmbAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbDataFinal;
    private javax.swing.JLabel lbDataInicio;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbProximaVacina;
    private javax.swing.JLabel lbProximaVisita;
    private javax.swing.JLabel lbUltimaVacina;
    private javax.swing.JLabel lbUltimaVisita;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDataFinal;
    private javax.swing.JTextField tfDataInicio;
    private javax.swing.JTextField tfProximaVacina;
    private javax.swing.JTextField tfProximaVisita;
    private javax.swing.JTextField tfUltimaVacina;
    private javax.swing.JTextField tfUltimaVisita;
    // End of variables declaration//GEN-END:variables
}
