package view;

/**
 * Frame criado para implementar o controle de doações de animail
 * @author Bernardelli
 * iniciada 30/03/2016
 */
public class FramePrincipal extends javax.swing.JFrame {

    
    
    public FramePrincipal() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        PanelPrimario = new javax.swing.JPanel();
        tpInicial = new javax.swing.JTabbedPane();
        PanelDoação = new javax.swing.JPanel();
        btDoação = new javax.swing.JButton();
        btAcompanhamento = new javax.swing.JButton();
        PanelCadastro = new javax.swing.JPanel();
        btDoador = new javax.swing.JButton();
        btAnimal = new javax.swing.JButton();
        btReceptor = new javax.swing.JButton();
        PanelImagem = new javax.swing.JPanel();
        lbImagem = new javax.swing.JLabel();
        mbPrincipal = new javax.swing.JMenuBar();
        mbArquivo = new javax.swing.JMenu();
        mbSobre = new javax.swing.JMenuItem();
        mbSair = new javax.swing.JMenuItem();
        mbOpções = new javax.swing.JMenu();
        mbDoador = new javax.swing.JMenuItem();
        mbAnimais = new javax.swing.JMenuItem();
        mbReceptor = new javax.swing.JMenuItem();
        mbDoação = new javax.swing.JMenuItem();
        mbAcompanhamento = new javax.swing.JMenuItem();
        mbRelatórios = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Doação de Animais 2.0");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setLocation(new java.awt.Point(400, 150));
        setResizable(false);

        PanelPrimario.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrimario.setAlignmentX(0.0F);
        PanelPrimario.setAlignmentY(0.0F);

        tpInicial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btDoação.setText("Realizar Doação");
        btDoação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoaçãoActionPerformed(evt);
            }
        });

        btAcompanhamento.setText("Acompanhar Doação");
        btAcompanhamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcompanhamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDoaçãoLayout = new javax.swing.GroupLayout(PanelDoação);
        PanelDoação.setLayout(PanelDoaçãoLayout);
        PanelDoaçãoLayout.setHorizontalGroup(
            PanelDoaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDoaçãoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PanelDoaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDoação, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAcompanhamento))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelDoaçãoLayout.setVerticalGroup(
            PanelDoaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDoaçãoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btDoação, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btAcompanhamento, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tpInicial.addTab("DOAÇÕES", PanelDoação);

        btDoador.setText("Doadores");
        btDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoadorActionPerformed(evt);
            }
        });

        btAnimal.setText("Animais");
        btAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnimalActionPerformed(evt);
            }
        });

        btReceptor.setText("Receptores");
        btReceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceptorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastroLayout = new javax.swing.GroupLayout(PanelCadastro);
        PanelCadastro.setLayout(PanelCadastroLayout);
        PanelCadastroLayout.setHorizontalGroup(
            PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btDoador, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        PanelCadastroLayout.setVerticalGroup(
            PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tpInicial.addTab("CADASTROS", PanelCadastro);

        PanelImagem.setBackground(new java.awt.Color(255, 255, 255));
        PanelImagem.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adoção.jpg"))); // NOI18N

        javax.swing.GroupLayout PanelImagemLayout = new javax.swing.GroupLayout(PanelImagem);
        PanelImagem.setLayout(PanelImagemLayout);
        PanelImagemLayout.setHorizontalGroup(
            PanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        PanelImagemLayout.setVerticalGroup(
            PanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImagemLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelPrimarioLayout = new javax.swing.GroupLayout(PanelPrimario);
        PanelPrimario.setLayout(PanelPrimarioLayout);
        PanelPrimarioLayout.setHorizontalGroup(
            PanelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrimarioLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelPrimarioLayout.setVerticalGroup(
            PanelPrimarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrimarioLayout.createSequentialGroup()
                .addComponent(PanelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelPrimarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        mbArquivo.setText("Arquivo");

        mbSobre.setText("Sobre");
        mbSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbSobreActionPerformed(evt);
            }
        });
        mbArquivo.add(mbSobre);

        mbSair.setText("Sair");
        mbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbSairActionPerformed(evt);
            }
        });
        mbArquivo.add(mbSair);

        mbPrincipal.add(mbArquivo);

        mbOpções.setText("Opções");

        mbDoador.setText("Cadastro Doador");
        mbDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbDoadorActionPerformed(evt);
            }
        });
        mbOpções.add(mbDoador);

        mbAnimais.setText("Cadastro Aninais");
        mbAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbAnimaisActionPerformed(evt);
            }
        });
        mbOpções.add(mbAnimais);

        mbReceptor.setText("Cadastro Receptor");
        mbReceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbReceptorActionPerformed(evt);
            }
        });
        mbOpções.add(mbReceptor);

        mbDoação.setText("Doação de Animais");
        mbDoação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbDoaçãoActionPerformed(evt);
            }
        });
        mbOpções.add(mbDoação);

        mbAcompanhamento.setText("Acompanhar Doação");
        mbAcompanhamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbAcompanhamentoActionPerformed(evt);
            }
        });
        mbOpções.add(mbAcompanhamento);

        mbRelatórios.setText("Relatórios");
        mbRelatórios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbRelatóriosActionPerformed(evt);
            }
        });
        mbOpções.add(mbRelatórios);

        mbPrincipal.add(mbOpções);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrimario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrimario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbSairActionPerformed
        dispose();
    }//GEN-LAST:event_mbSairActionPerformed

    private void mbSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbSobreActionPerformed
        FrameSobre frameSobre = new FrameSobre();
        frameSobre.setVisible(true);
    }//GEN-LAST:event_mbSobreActionPerformed

    private void btAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnimalActionPerformed
        FrameAnimal frameAnimal = new FrameAnimal();
        frameAnimal.setVisible(true);
    }//GEN-LAST:event_btAnimalActionPerformed

    private void btDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoadorActionPerformed
        FrameDoador frameDoador = new FrameDoador();
        frameDoador.setVisible(true);
    }//GEN-LAST:event_btDoadorActionPerformed

    private void btReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceptorActionPerformed
        FrameReceptor frameReceptor = new FrameReceptor();
        frameReceptor.setVisible(true);
    }//GEN-LAST:event_btReceptorActionPerformed

    private void btDoaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoaçãoActionPerformed
        FrameDoação frameDoação = new FrameDoação();
        frameDoação.setVisible(true);
    }//GEN-LAST:event_btDoaçãoActionPerformed

    private void btAcompanhamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcompanhamentoActionPerformed
        FrameAcompanhamento frameAcompanhamento = new FrameAcompanhamento();
        frameAcompanhamento.setVisible(true);
    }//GEN-LAST:event_btAcompanhamentoActionPerformed

    private void mbDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbDoadorActionPerformed
        FrameDoador frameDoador = new FrameDoador();
        frameDoador.setVisible(true);
    }//GEN-LAST:event_mbDoadorActionPerformed

    private void mbAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbAnimaisActionPerformed
        FrameAnimal frameAnimal = new FrameAnimal();
        frameAnimal.setVisible(true);
    }//GEN-LAST:event_mbAnimaisActionPerformed

    private void mbReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbReceptorActionPerformed
        FrameReceptor frameReceptor = new FrameReceptor();
        frameReceptor.setVisible(true);
    }//GEN-LAST:event_mbReceptorActionPerformed

    private void mbDoaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbDoaçãoActionPerformed
        FrameDoação frameDoação = new FrameDoação();
        frameDoação.setVisible(true);
    }//GEN-LAST:event_mbDoaçãoActionPerformed

    private void mbAcompanhamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbAcompanhamentoActionPerformed
        FrameAcompanhamento frameAcompanhamento = new FrameAcompanhamento();
        frameAcompanhamento.setVisible(true);
    }//GEN-LAST:event_mbAcompanhamentoActionPerformed

    private void mbRelatóriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbRelatóriosActionPerformed
        FrameRelatório frameRelatório = new FrameRelatório();
        frameRelatório.setVisible(true);
    }//GEN-LAST:event_mbRelatóriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        
            public void run() {
                
                new FramePrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCadastro;
    private javax.swing.JPanel PanelDoação;
    private javax.swing.JPanel PanelImagem;
    private javax.swing.JPanel PanelPrimario;
    private javax.swing.JButton btAcompanhamento;
    private javax.swing.JButton btAnimal;
    private javax.swing.JButton btDoador;
    private javax.swing.JButton btDoação;
    private javax.swing.JButton btReceptor;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JMenuItem mbAcompanhamento;
    private javax.swing.JMenuItem mbAnimais;
    private javax.swing.JMenu mbArquivo;
    private javax.swing.JMenuItem mbDoador;
    private javax.swing.JMenuItem mbDoação;
    private javax.swing.JMenu mbOpções;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem mbReceptor;
    private javax.swing.JMenuItem mbRelatórios;
    private javax.swing.JMenuItem mbSair;
    private javax.swing.JMenuItem mbSobre;
    private javax.swing.JTabbedPane tpInicial;
    // End of variables declaration//GEN-END:variables
}
